# Generated by Django 3.0.3 on 2020-04-24 20:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providerId', models.IntegerField()),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField(db_index=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='DataValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providerId', models.IntegerField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(db_index=True, default=list)),
            ],
        ),
    ]
